# Generated by Django 3.1.7 on 2021-03-05 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=400)),
                ('after_the_premiere', models.BooleanField(default=False)),
                ('the_premiere', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('last', models.IntegerField()),
                ('imdb', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Your review')),
                ('stars', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reviews', to='api.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=500)),
                ('movies', models.ManyToManyField(to='api.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=500)),
                ('birth', models.DateField(blank=True, null=True)),
                ('movies', models.ManyToManyField(to='api.Movie')),
            ],
        ),
    ]
